package com.example.Desings;

import com.example.Enums.Religion;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FormularioIncendioDesing extends FormLayout {

	TextField tipo;
	TextField titular;
	DateField hasta;
	NativeSelect<Religion> religion;
	RadioButtonGroup<String> enfermo;
	CheckBoxGroup<String> actividades;
	Button salvar;
	Button limpiar;
	
	public FormularioIncendioDesing() {
		Design.read(this);
	}
}
