package com.example.Desings;

import com.example.Enums.Religion;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ColorPicker;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Slider;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FormularioInundacionDesing extends FormLayout {

	TextField tipo;
	TextField titular;
	DateField hasta;
	NativeSelect<Religion> religion;
	Slider gusto;
	TextField bio;
	ColorPicker color;
	
	public FormularioInundacionDesing() {
		Design.read(this);
	}
}
